# Generated by Django 5.2.5 on 2025-09-17 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.library')),
            ],
            options={
                'permissions': [('can_add_book', 'Can add a new book'), ('can_change_book', 'Can change an existing book'), ('can_delete_book', 'Can delete a book')],
            },
        ),
    ]
