# Generated by Django 5.2.5 on 2025-09-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_book_author_remove_librarian_library_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book'), ('can_change_book', 'Can change an existing book'), ('can_delete_book', 'Can delete a book')]},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'permissions': [('can_add_library', 'Can add a new library'), ('can_change_library', 'Can change an existing library'), ('can_delete_library', 'Can delete a library')]},
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationship_app.library'),
        ),
        migrations.AlterField(
            model_name='library',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
