# Generated by Django 5.2.5 on 2025-09-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_alter_projectitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ProjectItem',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='published_date',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
