# Generated by Django 5.2.5 on 2025-10-25 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(db_index=True, max_length=255)),
                ('object_id', models.PositiveIntegerField(db_index=True, help_text='The primary key of the target object.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(help_text='The user who initiated the action.', on_delete=django.db.models.deletion.CASCADE, related_name='actions_made', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(help_text="The type of object the action was performed on (e.g., 'Post').", on_delete=django.db.models.deletion.CASCADE, related_name='target_notifications', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='The user who receives the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
